const A=document.getElementById('app');
let S={screen:'home',exam:null,type:null,i:null,sec:0,timer:null,paused:false,answer:'',result:null};
const names={ibps:{essay:'Essay Writing',comprehension:'Comprehension'},sbi:{email:'Email Writing',situation:'Situation Analysis',report:'Report Writing',precis:'Precis Writing',full:'Full Descriptive'}};
const meta={ibps:{title:'IBPS PO / MT-XVI',total:25,time:30},sbi:{title:'SBI PO 2026',total:30,time:30}};
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function stop(){clearInterval(S.timer);S.timer=null}
function reset(){stop();S={screen:'home',exam:null,type:null,i:null,sec:0,timer:null,paused:false,answer:'',result:null};render()}
function home(){reset()}
function choose(e){stop();S.exam=e;S.screen='types';render()}
function types(){stop();S.screen='types';render()}
function openType(t){stop();S.type=t;S.screen='tests';render()}
function data(){return SF[S.exam][S.type]||[]}
function render(){if(S.screen==='home')return homeView();if(S.screen==='types')return typeView();if(S.screen==='tests')return testList();if(S.screen==='test')return testView();if(S.screen==='patterns')return patternsView();if(S.screen==='scores')return scoreInfoView()}
function homeView(){A.innerHTML=`<section class="hero"><p class="eyebrow">Free PO descriptive practice · no login</p><h1>Write better.<br>Practice smarter.</h1><p class="lead">SCOREFREE gives you timed writing practice, a transparent practice score and learning pointers after every attempt — without pretending that AI-generated prompts are PYQs.</p><div class="hero-actions"><button class="primary" onclick="choose('ibps')">Practice IBPS PO →</button><button class="secondary" onclick="choose('sbi')">Practice SBI PO →</button></div></section><div class="section-title"><div><p class="eyebrow">Choose your exam</p><h2>Build exam-ready writing habits</h2></div><button class="ghost" onclick="patterns()">View official pattern →</button></div><div class="grid"><div class="card"><span class="badge">IBPS PO / MT-XVI</span><h2>Essay + Comprehension</h2><p class="muted">2 descriptive questions · 25 marks · 30 minutes. Individual practice is shorter so you can drill one skill.</p><button class="primary" onclick="choose('ibps')">View practice</button></div><div class="card"><span class="badge coral">SBI PO 2026</span><h2>Communication Skills</h2><p class="muted">Email + Situation Analysis + Report/Precis choice · 30 marks · 30 minutes in the official 2026 advertisement.</p><button class="primary" onclick="choose('sbi')">View practice</button></div></div><div class="notice" style="margin-top:18px"><b>Integrity first:</b> reported previous-year questions are labelled separately. Practice prompts are original and are never presented as PYQs.</div>`}
function typeView(){let keys=Object.keys(names[S.exam]);A.innerHTML=`<button class="back" onclick="home()">← Back</button><p class="eyebrow">${meta[S.exam].title}</p><h1 style="font-size:clamp(2.4rem,6vw,4.6rem)">What do you want to practice?</h1><p class="lead">Choose one skill. Each focused test uses a 15-minute practice timer with pause, resume and early submission.</p><div class="types">${keys.map(k=>{let d=SF[S.exam][k];let pyq=d.filter(q=>q[0]==='PYQ').length;return `<div class="card type"><div><h3>${names[S.exam][k]}</h3><div class="count"><strong>${d.length}</strong> tests · ${pyq} reported PYQ${pyq===1?'':'s'}</div></div><button class="primary" onclick="openType('${k}')">Open →</button></div>`}).join('')}</div>`}
function testList(){let d=data();A.innerHTML=`<button class="back" onclick="types()">← Back to ${meta[S.exam].title}</button><p class="eyebrow">${meta[S.exam].title}</p><h1 style="font-size:clamp(2.2rem,5vw,4.3rem)">${names[S.exam][S.type]}</h1><p class="lead">50 tests are available in this practice bank. Reported PYQs are marked; the rest are original practice so you always know what you are attempting.</p><div class="notice"><b>Scoring:</b> your result is a SCOREFREE practice estimate, not an official bank-issued score. Official notifications state the paper marks and timing but do not publish a detailed item-by-item writing rubric.</div><div class="tests">${d.map((q,i)=>`<button class="test" onclick="start(${i})"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="tag ${q[0]==='PYQ'?'pyq':'practice'}">${q[0]==='PYQ'?'Reported PYQ':'Practice'}</span><span class="small">${q[1]} · ${esc(q[2]).slice(0,95)}${q[2].length>95?'…':''}</span></button>`).join('')}</div>`}
function start(i){S.i=i;S.answer='';S.result=null;S.screen='test';S.sec=900;S.paused=false;render();clock()}
function clock(){stop();S.timer=setInterval(()=>{if(!S.paused){S.sec--;update()}if(S.sec<=0){S.sec=0;stop();update();document.getElementById('status').textContent='Time is up — you may still submit your answer.'}},1000)}
function update(){let x=document.getElementById('timer');if(x){x.textContent=fmt(S.sec);x.classList.toggle('warn',S.sec<=120)}}
function pause(){S.paused=!S.paused;document.getElementById('pause').textContent=S.paused?'▶ Resume':'⏸ Pause';document.getElementById('status').textContent=S.paused?'Timer paused':''}
function count(){let a=document.getElementById('answer');if(!a)return;S.answer=a.value;let words=wordCount(S.answer),w=document.getElementById('wc');if(w)w.textContent=words}
function wordCount(s){return String(s||'').trim()?String(s).trim().split(/\s+/).length:0}
function taskRules(){if(S.exam==='sbi'){return {email:{max:10,criteria:['Purpose & relevance','Professional format','Clarity & tone','Completeness']},situation:{max:10,criteria:['Issue identification','Judgement & ethics','Action plan','Clarity']},report:{max:10,criteria:['Structure & facts','Findings','Recommendations','Language']},precis:{max:10,criteria:['Central idea','Coverage','Concision','Language']},full:{max:30,criteria:['Task completion','Structure','Relevance','Language']}}}return {essay:{max:25,criteria:['Relevance & depth','Organisation','Examples / reasoning','Language']},comprehension:{max:25,criteria:['Passage understanding','Evidence / accuracy','Concise expression','Language']}}}
function wordRule(){if(S.exam==='sbi'&&S.type==='precis')return {title:'Official SBI training guidance',text:'Normally one-third of the source passage. Follow the exact word limit stated in the question.',fixed:false};return {title:'Official 2026 word-limit status',text:'No universal word limit is published in the current official 2026 notification for this task. Follow the word limit stated in the actual question.',fixed:false}}
function evaluate(q,answer){const text=String(answer||'').trim(),w=wordCount(text),r=taskRules()[S.type],max=r.max;let lower=text.toLowerCase();let relevance=0,structure=0,language=0,completeness=0;const keywords=(q[4]||'').toLowerCase().split(/[,.;:]/).flatMap(x=>x.split(/\s+/)).filter(x=>x.length>4).slice(0,12);let hits=keywords.filter(k=>lower.includes(k)).length;relevance=Math.min(1,hits/Math.max(4,Math.min(8,keywords.length)));const paras=text.split(/\n\s*\n/).filter(Boolean).length;structure=Math.min(1,(paras>=3?.45:paras>=2?.3:.12)+(/[.!?]/.test(text)?.2:0)+(/[,:;]/.test(text)?.15:0));const sentences=text?text.split(/[.!?]+/).filter(Boolean):[];const avg=sentences.length?w/sentences.length:0;language=Math.min(1,(sentences.length>=4?.3:.1)+(avg>=8&&avg<=30?.3:.12)+( /\b(the|and|but|because|however|therefore|also)\b/i.test(text)?.18:0)+(/[A-Z][^.!?]*[.!?]/.test(text)?.15:0));completeness=Math.min(1,(w>0?.25:0)+(sentences.length>=3?.25:0)+(w>=80?.25:0)+(paras>=2?.25:0));if(/^(subject|to|from|dear|title|report)/im.test(text))structure+=.12;let total=Math.max(0,Math.min(max,Math.round(max*(relevance*.28+structure*.24+language*.24+completeness*.24))));return {total,max,breakdown:{relevance:Math.round(relevance*100),structure:Math.min(100,Math.round(structure*100)),language:Math.round(language*100),completeness:Math.round(completeness*100)},words:w}}
function testView(){let q=data()[S.i];let score=S.result?resultView(q,S.result):`<div class="prompt"><div class="prompttext"><span class="tag ${q[0]==='PYQ'?'pyq':'practice'}">${q[0]==='PYQ'?'Reported PYQ':'Practice'}</span><p class="small">${q[1]}</p><h2>${esc(q[2])}</h2><p>${esc(q[3])}</p><div class="learn-strip"><div><b>Learn while you write</b><span>${esc(q[4])}</span></div><div class="word-rule"><b>${wordRule().title}</b><span>${wordRule().text}</span></div></div><div class="answerbox"><textarea id="answer" class="textarea" placeholder="Type your answer here…" oninput="count()">${esc(S.answer)}</textarea><div class="words"><span id="wc">${wordCount(S.answer)}</span> words</div></div></div></div><div class="actions"><button class="secondary" id="pause" onclick="pause()">⏸ Pause</button><button class="primary" onclick="submit()">Submit & score →</button></div><p class="small" id="status" style="text-align:right">You can submit before the timer ends.</p>`;A.innerHTML=`<div style="max-width:960px;margin:auto"><button class="back" onclick="types()">← Exit test</button><div class="testhead"><div><p class="eyebrow">${meta[S.exam].title} · ${names[S.exam][S.type]}</p><h2>Practice Test ${String(S.i+1).padStart(2,'0')}</h2><span class="small">${q[0]==='PYQ'?'Reported PYQ':'Original practice'} · 15-minute focused practice</span></div><div class="timerbox"><div class="timer" id="timer">${fmt(S.sec)}</div><div class="small" id="status">${S.paused?'Timer paused':''}</div></div></div>${score?score:''}</div>`;if(S.result){stop()}else{let a=document.getElementById('answer');if(a){a.focus();a.setSelectionRange(a.value.length,a.value.length)}}}
function submit(){let a=document.getElementById('answer');S.answer=a?a.value:S.answer;stop();S.result=evaluate(data()[S.i],S.answer);saveResult();render()}
function resultView(q,r){let ratio=r.total/r.max*100;let labels=taskRules()[S.type].criteria;let keys=['relevance','structure','language','completeness'];return `<div class="feedback"><div class="scorecard"><p class="eyebrow">Practice score</p><div class="scorebig">${r.total}<span style="font-size:1.2rem;color:var(--muted)"> / ${r.max}</span></div><div class="scorebar"><div class="scorefill" style="width:${ratio}%"></div></div><p class="muted">${scoreMessage(ratio)} · ${r.words} words typed</p><div class="rubric">${keys.map((k,i)=>`<div><div class="rubric-row"><span><b>${labels[i]||k}</b></span><span>${r.breakdown[k]}%</span></div><div class="mini-bar"><div class="mini-fill" style="width:${r.breakdown[k]}%"></div></div></div>`).join('')}</div><p class="score-note" style="margin-top:17px">This is a transparent SCOREFREE practice estimate. It is not an official IBPS/SBI examiner score.</p></div><div class="learncard"><p class="eyebrow">What to learn from this test</p><h3>${esc(q[2])}</h3><p>${esc(q[4])}</p><ul><li>Keep the opening directly connected to the task.</li><li>Use short paragraphs and one clear idea per paragraph.</li><li>Prefer specific, relevant points over decorative language.</li><li>Leave the final minute for grammar, spelling and completeness.</li></ul><div class="result-actions"><button class="primary" onclick="retry()">Try again</button><button class="secondary" onclick="openType('${S.type}')">More ${names[S.exam][S.type]}</button></div></div></div>`}
function scoreMessage(p){return p>=85?'Strong attempt':p>=70?'Good base — polish the weak areas':p>=50?'Decent start — work on structure and relevance':'Needs more practice — focus on the checklist first'}
function retry(){S.result=null;S.answer='';S.sec=900;S.paused=false;render();clock()}
function patterns(){stop();S.screen='patterns';render()}
function patternsView(){A.innerHTML=`<button class="back" onclick="home()">← Back</button><p class="eyebrow">Official 2026 pattern</p><h1 style="font-size:clamp(2.5rem,6vw,4.7rem)">Know the paper.</h1><div class="pattern-grid"><div class="pattern-card"><span class="badge">IBPS PO / MT-XVI</span><h2>Descriptive Paper</h2><p>Essay + Comprehension · 2 questions · <b>25 marks</b> · <b>30 minutes</b> · English.</p><div class="stat-row"><span class="stat">Current 2026 notification</span><span class="stat">No 2026 PYQ yet</span></div></div><div class="pattern-card"><span class="badge coral">SBI PO 2026</span><h2>Communication Skills</h2><p>Emails (1 of 2), Situation Analysis (1 of 2), and either Reports or Precis (1 of 2) · <b>30 marks</b> · <b>30 minutes</b> · English.</p><div class="stat-row"><span class="stat">3 responses</span><span class="stat">Official 2026 advertisement</span></div></div></div><div class="notice" style="margin-top:18px"><b>Important correction:</b> the official SBI PO 2026 advertisement currently states a <b>30-mark</b> descriptive test. Some websites still show 50 marks or the 2025 revised pattern, so SCOREFREE follows the current official 2026 advertisement.</div><div class="section-title"><div><p class="eyebrow">Scoring</p><h2>What SCOREFREE can and cannot score</h2></div></div><div class="card"><p class="muted"><b>Word limits:</b> the current official 2026 IBPS PO/MT-XVI and SBI PO 2026 notifications do not publish a universal fixed word limit for these descriptive tasks. SCOREFREE therefore does <b>not</b> invent one. Follow the limit stated in the actual question. For précis, official SBI training guidance says it is normally one-third of the source passage, subject to the question’s instruction.</p><p class="muted"><b>Scoring:</b> the banks publish marks, duration and task structure, but not a public item-by-item writing formula. SCOREFREE uses a transparent practice rubric for learning; it is not an official examiner score.</p></div>`}
function aboutScores(){S.screen='scores';stop();render()}
function scoreInfoView(){A.innerHTML=`<button class="back" onclick="home()">← Back</button><p class="eyebrow">Transparent evaluation</p><h1 style="font-size:clamp(2.5rem,6vw,4.6rem)">Score it. Learn from it.</h1><div class="grid"><div class="card"><h2>Relevance</h2><p class="muted">Did you address the actual task and include useful, topic-specific points?</p></div><div class="card"><h2>Structure</h2><p class="muted">Is the response easy to follow, with an appropriate format and logical flow?</p></div><div class="card"><h2>Language</h2><p class="muted">Are sentences clear, professional and reasonably accurate?</p></div><div class="card"><h2>Completeness</h2><p class="muted">Did you cover the requested elements and develop the response enough to be useful? Word count is shown for practice, but SCOREFREE does not invent an official word limit.</p></div></div><div class="notice" style="margin-top:18px"><b>Not an official marking formula:</b> banks do not publicly provide a detailed writing-score algorithm. This is deliberately shown as a practice estimate rather than a fake “official AI score”.</div>`}
function saveResult(){let key='sf-history';let old=JSON.parse(localStorage.getItem(key)||'[]');old.unshift({date:new Date().toLocaleString(),exam:S.exam,type:S.type,test:S.i+1,score:S.result.total,max:S.result.max});localStorage.setItem(key,JSON.stringify(old.slice(0,20)))}
render();
