/* SCOREFREE editorial-style passage engine
   Passages are ORIGINAL practice writing. Topics can be informed by current
   newspaper/editorial/explainer discussions, but source articles are never
   reproduced verbatim. This file is a runtime fallback for compact legacy
   entries while the curated passage bank is being expanded.
*/
(function(){
  if(!window.SF) return;
  const wc=s=>String(s||'').trim().split(/\s+/).filter(Boolean).length;
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const lower=s=>clean(s).toLowerCase();
  const has=(t, words)=>words.some(w=>t.includes(w));

  const banks={
    economy:[
      'Economic growth is often discussed through headline indicators, but the quality of growth matters as much as its pace. A country may record expanding output while households continue to face uneven incomes, uncertain employment and rising costs. This makes the relationship between growth and everyday welfare an important subject of public policy. The challenge is not merely to increase production, but to create conditions in which investment, employment and productivity reinforce one another over time.',
      'External conditions add another layer of uncertainty. Changes in global interest rates, commodity prices, trade demand and geopolitical tensions can affect an open economy even when domestic fundamentals remain relatively stable. Policymakers therefore have to balance short-term support with longer-term resilience. Excessive stimulus can create inflationary pressure, while an overly cautious approach can weaken demand and investment. Sound policy requires judging these trade-offs rather than relying on a single indicator.',
      'Domestic demand can provide an important cushion when external demand weakens, but it cannot substitute indefinitely for competitive exports and productive investment. Businesses need predictable regulation, efficient logistics, access to finance and skilled workers. Smaller enterprises often face these constraints more sharply than large firms. Improving the business environment therefore involves more than announcing incentives; it requires reducing the everyday costs and uncertainties that discourage firms from expanding.',
      'Employment is central to the social meaning of economic growth. New investment can generate jobs directly and indirectly, yet the benefits depend on the skills of workers and the ability of firms to absorb them. If new opportunities are concentrated in a few locations or require specialised capabilities, many workers may remain outside the growth process. Education, vocational training and mobility support can help narrow this gap, but they must be linked to actual demand in the labour market.',
      'The distributional consequences of economic policy also deserve attention. Inflation, for instance, does not affect every household equally because spending patterns differ. A rise in the price of food or transport can consume a much larger share of a low-income household budget than of a high-income household. Policy responses should therefore consider who bears the cost of adjustment. A resilient economy is one in which vulnerable households have enough protection to withstand temporary shocks without losing their long-term prospects.',
      'Ultimately, sustainable growth depends on institutions that can respond to changing circumstances without sacrificing credibility. Governments, regulators and businesses each have different responsibilities, and coordination becomes especially important during periods of uncertainty. Transparent communication can reduce confusion, while timely data can help policymakers distinguish a temporary disturbance from a structural weakness. The objective should be an economy that is productive, adaptable and capable of generating broad-based opportunities.'
    ],
    banking:[
      'Banking is changing rapidly as customers move from branches and paper-based processes towards mobile applications and instant payments. The convenience is considerable: routine transactions can be completed at any hour, and financial services can reach people who live far from a branch. Yet digital access should not be mistaken for complete financial inclusion. A customer may have a bank account and still lack the confidence, literacy or connectivity needed to use it safely and effectively.',
      'Digital banking also changes the nature of risk. A physical branch creates a visible point of contact, whereas an online transaction may involve several institutions, devices and authentication layers. Fraudsters exploit weak passwords, social engineering and hurried decisions as much as technical vulnerabilities. Security therefore cannot be treated solely as a matter for engineers. Customers need understandable warnings, banks need effective monitoring, and regulators need rules that encourage innovation without allowing avoidable risks to spread.',
      'The growth of instant payment systems has also raised questions about the economics of banking. Faster transactions can lower friction for consumers and merchants, but banks and payment providers still need sustainable business models. Competition can improve services, yet excessive dependence on a small number of platforms can create concentration risks. Interoperability, resilient infrastructure and clear liability rules become important when a payment system handles a very large volume of everyday transactions.',
      'Credit is another area where convenience must be balanced with responsibility. Digital lending can shorten the time between an application and a decision, but speed can become harmful if borrowers do not understand the cost of credit. Automated models may also rely on data that contain hidden biases or errors. Responsible lending requires transparent terms, appropriate assessment of repayment capacity and mechanisms through which customers can challenge incorrect information.',
      'Financial inclusion has a wider meaning than opening accounts. People need savings products, affordable credit, insurance and reliable payment facilities that match their circumstances. Women, small businesses, migrants and people in remote areas can face different barriers. Policies that expand access should therefore be accompanied by financial education and local support. Inclusion becomes durable when people can use financial services confidently rather than merely possessing an account that remains inactive.',
      'The future of banking will therefore depend on finding a balance between innovation and trust. Technology can make finance faster and more accessible, but trust is built through reliability, privacy, fair treatment and quick resolution of problems. The strongest systems will not be those that digitise every interaction regardless of circumstance. They will be those that use technology where it improves outcomes while retaining meaningful human support when customers need explanation, protection or redress.'
    ],
    technology:[
      'Technology is increasingly presented as a solution to problems ranging from productivity and education to healthcare and public administration. Yet technology rarely produces social benefits automatically. Its impact depends on how it is designed, who can access it and what institutions do when the system fails. A new tool can reduce routine work while creating new demands for oversight, training and judgement. The central policy question is therefore not whether technology should be adopted, but how it should be adopted responsibly.',
      'Artificial intelligence has made this debate more urgent because it can perform tasks that were once associated with human reasoning. Businesses see opportunities to improve productivity and reduce repetitive work, while workers worry about displacement and changing skill requirements. Both possibilities can exist at the same time. Some occupations may shrink, others may change, and entirely new roles may emerge. The transition will depend heavily on whether workers have opportunities to acquire relevant skills before technological change leaves them behind.',
      'The quality of data is another fundamental issue. Automated systems learn from information collected in the real world, and that information may contain omissions, historical inequalities or measurement errors. If such weaknesses are not recognised, a system can reproduce them at scale. Transparency about how a model is used, what information it considers and how people can appeal a decision is therefore essential, particularly when automated decisions affect employment, credit, education or access to public services.',
      'There is also a question of concentration. Advanced digital infrastructure requires capital, computing resources and specialised expertise, which can give a small number of companies considerable influence. Competition policy and open standards can help prevent technological progress from becoming excessive dependence on a handful of providers. At the same time, regulation must be flexible enough to distinguish genuine risks from ordinary experimentation. A rule that is too weak may fail to protect users; one that is too rigid may discourage useful innovation.',
      'Technology can also widen existing inequalities if access to devices, connectivity and digital skills remains uneven. A service that is entirely online may appear efficient from the perspective of an institution while becoming inaccessible to someone with poor connectivity or limited digital literacy. Designing for inclusion means keeping alternative channels available, simplifying interfaces and testing products with diverse users. Accessibility should be treated as part of good design rather than as an afterthought.',
      'The most useful approach is therefore neither blind enthusiasm nor blanket resistance. Societies need institutions capable of evaluating technologies according to evidence, public value and risk. Workers need opportunities to learn continuously, and users need clear rights and effective remedies. When innovation is combined with accountability, technology can strengthen productivity and public services without weakening human agency. The objective should be to make technology serve social goals rather than allowing technological capability to determine those goals by itself.'
    ],
    labour:[
      'The world of work is changing as businesses respond to technology, global competition and shifting consumer behaviour. Flexible arrangements can give workers greater control over their schedules and can help companies respond quickly to demand. Yet flexibility can also transfer uncertainty from firms to workers. When income varies sharply, benefits are limited and employment can end without much notice, the worker bears risks that were previously shared through more stable employment arrangements.',
      'The debate over gig work illustrates this tension. Platform-based work can provide an accessible entry point for people who need immediate income, and it can be especially useful for those seeking flexible hours. But flexibility is meaningful only when workers have enough bargaining power to make choices. If a person accepts every available assignment because refusing work threatens their income, nominal flexibility may conceal considerable economic dependence.',
      'Social security becomes particularly important in such an environment. Traditional employment systems often connect health coverage, retirement savings and other benefits to a formal employer. Workers who move between platforms or combine several sources of income may fall outside these arrangements. New forms of work therefore require institutions to think beyond the simple employer-employee relationship and consider portable protections that can follow workers across jobs.',
      'Skills policy is equally important. Technological change does not eliminate the need for labour, but it can alter which skills are rewarded. Workers may need stronger digital abilities, problem-solving skills or sector-specific knowledge. Training programmes are most effective when they are linked to real vacancies and are accessible to people who cannot afford to leave paid work for long periods. Employers, educational institutions and governments all have a role in closing this gap.',
      'Labour markets also reflect broader social inequalities. Women, migrants and workers from poorer households may enter flexible work because formal opportunities are scarce. A policy that celebrates flexibility without examining why people choose it can therefore overlook structural constraints. Better employment policy should measure not only the number of jobs created but also earnings, stability, safety, mobility and opportunities for progression.',
      'The future of work will probably contain a mixture of permanent employment, contract work, platform-based activity and self-employment. Rather than trying to force every worker into one category, policy should ensure that basic standards of dignity, safety and social protection are maintained across categories. Economic dynamism and worker protection need not be opposing objectives. A labour market is more resilient when people can adapt to change without being pushed into severe insecurity.'
    ],
    climate:[
      'Climate policy is often framed as a choice between environmental protection and economic development, but that framing is increasingly inadequate. Energy, transport, agriculture, housing and industry all depend on natural resources, while climate-related disruptions can damage infrastructure and household incomes. The practical challenge is to make development more resilient while gradually reducing the environmental costs associated with production and consumption.',
      'For a developing economy, the transition is particularly complex. Millions of people still require reliable and affordable energy, and industrial expansion remains important for employment. At the same time, investments made today can lock economies into infrastructure that is expensive to replace later. This makes long-term planning important. Cleaner technologies need to become economically viable, while workers and regions dependent on carbon-intensive activities need support during the transition.',
      'Climate impacts are also unevenly distributed. A wealthy household may be able to cope with extreme heat by using cooling equipment or moving temporarily, while a low-income worker may have to continue working outdoors. Farmers can be exposed to changing rainfall patterns without having the resources to absorb a failed harvest. Climate policy must therefore be connected with social policy. Adaptation measures such as resilient infrastructure, early-warning systems and better insurance can reduce the burden on vulnerable communities.',
      'The financing of the transition presents another challenge. Renewable energy, public transport, efficient buildings and resilient water systems require large investments whose benefits may appear over many years. Governments must therefore create conditions that attract private capital while ensuring that public interest is not weakened. Stable rules, credible institutions and transparent project selection can reduce uncertainty and make long-term investment easier.',
      'Technology alone will not solve the climate problem. Efficiency gains can be cancelled by rising consumption, and a new technology may create environmental costs elsewhere in its supply chain. Policies should therefore consider the full life cycle of products and infrastructure. Recycling, efficient use of materials, urban planning and behavioural change can complement technological innovation.',
      'A credible climate strategy ultimately depends on consistency. Ambitious targets are useful only when they are translated into budgets, infrastructure, regulations and measurable progress. The transition should also be fair: communities that have contributed least to the problem but face high risks should not be left to bear disproportionate costs. Climate action is strongest when environmental responsibility and economic opportunity are pursued together rather than treated as separate agendas.'
    ],
    education:[
      'Education is frequently measured through enrolment, examination results and years spent in school, but these indicators do not fully capture whether students are acquiring useful capabilities. A good education system should help learners understand ideas, communicate clearly, solve unfamiliar problems and continue learning after formal schooling ends. This becomes particularly important when technology and labour markets change faster than curricula can be rewritten.',
      'The expansion of digital learning has created new possibilities but has also exposed old inequalities. Online resources can reach students beyond the classroom and allow lessons to be revisited at a convenient pace. Yet access to a device or internet connection does not guarantee effective learning. Students need quiet spaces, guidance, suitable content and opportunities to ask questions. Teachers therefore remain central even when technology becomes more prominent.',
      'Assessment also deserves reconsideration. Examinations can provide a common benchmark, but excessive dependence on high-stakes testing may encourage memorisation at the expense of curiosity and application. A stronger system would combine examinations with projects, practical work and opportunities to demonstrate reasoning. Such approaches require careful design because assessment must remain reliable and fair across different schools and regions.',
      'Teacher quality is another foundation. Recruitment matters, but so do professional development, classroom support and manageable workloads. Teachers are expected to respond to different learning levels within the same classroom, often with limited resources. Investments in training are therefore most effective when schools also provide the time and institutional support needed to apply new methods.',
      'The connection between education and employment must also be strengthened without reducing education to job training. Young people need both specialised knowledge and transferable skills. Communication, quantitative reasoning, digital literacy and teamwork can remain valuable even when specific occupations change. Partnerships between educational institutions and employers can help identify emerging needs while preserving room for broad learning.',
      'The long-term goal should be an education system that expands opportunity rather than reproducing existing inequalities. That requires attention to infrastructure, language, disability access, gender and household circumstances. Technology can help, but it cannot replace sustained investment in teachers and institutions. Education becomes transformative when learners are not merely prepared to pass an examination but are equipped to participate confidently in economic and civic life.'
    ],
    governance:[
      'Good governance is often associated with large reforms, but much of its impact is experienced through ordinary interactions between citizens and institutions. A certificate issued on time, a grievance resolved fairly or a public service delivered without repeated visits can make a significant difference to people. Administrative efficiency therefore matters not because speed is valuable by itself, but because delays can impose financial and emotional costs on citizens, particularly those with limited resources.',
      'Digitisation has become a major instrument for improving public administration. Online applications, electronic records and direct transfers can reduce paperwork and make processes easier to monitor. However, digitisation can also create new barriers when people lack connectivity, documentation or digital confidence. A public service should therefore not be judged solely by whether it has an online portal. The real test is whether eligible citizens can access it reliably and whether those who face difficulties have an alternative route to assistance.',
      'Transparency is closely connected with trust. Institutions are more credible when people can understand the rules governing a decision and know where to seek clarification. Complex procedures can create opportunities for discretion, but discretion without accountability can become arbitrary. Simplifying rules, publishing clear information and maintaining records of decisions can reduce uncertainty while allowing officials to deal with genuine exceptional cases.',
      'Data can improve governance by revealing patterns that are otherwise difficult to see. Yet collecting more data does not automatically produce better decisions. Information must be accurate, relevant and protected from misuse. Citizens should know, where appropriate, why their information is being collected and how it will be used. Strong safeguards are especially important when databases influence access to welfare, credit, healthcare or other essential services.',
      'Local institutions also deserve attention. Policies designed nationally may produce different results across regions because infrastructure, language, administrative capacity and social conditions vary. Effective implementation therefore requires feedback from the ground. Local officials and communities can identify practical obstacles that may not be visible in central planning documents.',
      'Ultimately, governance should be evaluated by outcomes and accountability rather than by the number of schemes announced. Institutions earn confidence when they deliver consistently, explain decisions and correct mistakes. Reform is most durable when it combines technology with human judgement, clear rules with flexibility for exceptional cases, and efficiency with fairness.'
    ],
    agriculture:[
      'Agriculture remains closely connected to food security, rural incomes and the wider economy, even as the structure of employment changes. Farmers make decisions under uncertainty because weather, prices, input costs and market access can change between planting and harvest. Improving farm incomes therefore requires more than increasing production. It requires reducing avoidable risks and helping farmers obtain better returns from what they produce.',
      'Climate variability has made this challenge more complex. Irregular rainfall, heat stress and extreme weather can affect yields and the timing of farm operations. Irrigation, water conservation, crop diversification and better forecasting can reduce some of these risks, but their effectiveness depends on local conditions. A technology that works for a large irrigated farm may not be suitable for a smallholder with limited capital.',
      'Market access is equally important. Better roads, storage and processing facilities can reduce losses and allow farmers to sell when prices are more favourable. Digital platforms may improve access to information, but information is useful only when farmers have real choices about where and when to sell. Producer organisations and cooperatives can strengthen bargaining power by allowing smaller producers to aggregate output and share services.',
      'Agricultural policy must also consider the relationship between incentives and sustainability. Support that encourages a particular crop can influence water use, soil health and regional cropping patterns for years. As dietary demand and climate conditions change, policies may need to encourage a more diversified production system. Such transitions should be gradual and supported by research, extension services and reliable markets.',
      'Rural development cannot depend on farming alone. Small businesses, food processing, logistics and local services can create non-farm employment and reduce pressure on agricultural land. Better connectivity can allow rural enterprises to reach wider markets, while skills programmes can help young people choose between farming, entrepreneurship and wage employment.',
      'A resilient rural economy is therefore one that gives households several ways to manage risk. Farmers need productive assets and market opportunities, but they also need access to credit, insurance, information and public infrastructure. The objective should be to make rural communities less vulnerable to a single bad season while creating pathways for long-term productivity and income growth.'
    ]
  };

  function chooseBank(topic){
    const t=lower(topic);
    if(has(t,['bank','rbi','credit','loan','deposit','upi','payment','financial','rupee','currency','digital lending'])) return banks.banking;
    if(has(t,['ai','artificial intelligence','technology','semiconductor','chip','digital','cyber','social media','automation'])) return banks.technology;
    if(has(t,['job','employment','labour','labor','gig','worker','workforce','wage','unemployment','manufacturing'])) return banks.labour;
    if(has(t,['climate','environment','green','carbon','renewable','energy','pollution','net zero'])) return banks.climate;
    if(has(t,['education','school','learning','student','skill','teacher','university'])) return banks.education;
    if(has(t,['agriculture','farmer','farm','crop','rural','food security'])) return banks.agriculture;
    if(has(t,['government','governance','policy','public service','judiciary','administration','welfare'])) return banks.governance;
    return banks.economy;
  }

  function extend(q){
    const base=clean(q[5]);
    if(!base || wc(base)>=500) return;
    const topic=clean(q[2]);
    const bank=chooseBank(topic);
    let text=base;
    for(const p of bank){
      if(wc(text)>=500) break;
      text += '\n\n' + p;
    }
    q[5]=text;
    q[4]=(clean(q[4])||'').replace(/\s*$/,'') + ' Original SCOREFREE practice passage; topic informed by newspaper/editorial-style discussions. Not an official exam passage.';
  }

  const apply=(arr)=>{ if(Array.isArray(arr)) arr.forEach(extend); };
  apply(window.SF.ibps && window.SF.ibps.comprehension);
  apply(window.SF.sbi && window.SF.sbi.precis);
})();
